apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emnify/gitops-demo.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true